/**
 * Dexie schema definition.
 *
 * The schema is expressed as an ordered list of versioned migrations. Every
 * future schema change appends a new {@link SchemaVersion} (version bump +
 * store delta) — existing entries are never edited (docs/03_DATA_LAYER.md §8).
 *
 * Stage 1 shipped only an infrastructure `meta` key/value table (used for the
 * device id and stored schema metadata). Stage 2 (version 2) introduces the
 * `accounts` table — the first financial domain. Later domain tables
 * (transactions, budgets, …) append further versions.
 *
 * Index notes for domain tables: `&id` is the unique primary key (a UUID v4
 * generated by the repository); the remaining fields are secondary indexes for
 * the queries each domain runs (e.g. filtering active rows by `deletedAt`).
 */

/** Dexie store name for the accounts domain (docs/03_DATA_LAYER.md §3). */
export const ACCOUNTS_TABLE = 'accounts';

export interface SchemaVersion {
  readonly version: number;
  /** Dexie store definitions: table name → indexed properties. */
  readonly stores: Readonly<Record<string, string>>;
}

export const DATABASE_NAME = 'cuentas';

export const schemaVersions: readonly SchemaVersion[] = [
  {
    version: 1,
    stores: {
      // Key/value metadata, e.g. deviceId, schemaVersion. `&key` = unique primary key.
      meta: '&key',
    },
  },
  {
    version: 2,
    stores: {
      // Accounts domain (Stage 2). Indexed by name/type for listing and grouping,
      // and by deletedAt so active-row queries avoid full scans.
      [ACCOUNTS_TABLE]: '&id, name, type, deletedAt',
    },
  },
];

/** Highest declared schema version. */
export const CURRENT_SCHEMA_VERSION: number = schemaVersions.reduce(
  (max, entry) => Math.max(max, entry.version),
  0,
);

/** Shape of a row in the `meta` table. */
export interface MetaRecord {
  readonly key: string;
  readonly value: string;
}
